weight_file: "../ckpts/best_ckpt.pth"
detector_model: "DR-SPAAM"  # DROW3 or DR-SPAAM
conf_thresh: 0.95
stride: 2  # use this to skip laser points
panoramic_scan: True  # Set to true if the scan covers 360 degree
