publisher:
    detections:
        topic: /dr_spaam_detections
        queue_size: 1
        latch: false

    rviz:
        topic: /dr_spaam_rviz
        queue_size: 1
        latch: false

subscriber:
    scan:
        topic: /segway/scan_multi
        queue_size: 1
